FROM node:20

WORKDIR /app

# Установка NestJS CLI и netcat-openbsd (реализация nc)
RUN npm install -g @nestjs/cli \
    && apt-get update \
    && apt-get install -y netcat-openbsd \
    && rm -rf /var/lib/apt/lists/*

COPY package.json ./
RUN npm install

COPY . .

CMD ["npm", "run", "start:dev"]