import { Box, Typography, TextField, Chip } from "@mui/material";

export const TopImagesBox = () => {
  const tags = [
    "Эльфы", "Фэнтези", "Приключения", "Магия", 
    "Лес", "Драконы", "Приключенческий", "Сказка", 
    "Мифология", "Супергерои", "Волшебство", "Герои", 
    "Загадки", "Сражения", "Квесты", "Древние", 
    "Существа", "Тайны", "Путешествия", "Сказочные", 
    "Мифические", "Легенды", "Судьба", "Свет", 
    "Тьма", "Силы", "Друзья", "Враги", "Судьбы"
  ];

  const handleTagClick = (tag) => {
    console.log(`Tag clicked: ${tag}`);
    // You can add more functionality here, like filtering or searching based on the tag
  };

  return (
    <Box width="100%" flexDirection={"column"} display={"flex"} position="relative">
      <img 
        style={{ 
          objectFit: 'cover', 
          objectPosition: 'top', // Aligns the image to the top
          height: '1000px', 
          width: '100%' // Ensures the image takes the full width
        }}  
        src="./public/photo_2024-11-25_21-31-36.jpg" 
        alt="Top Image"
      />
      <Box 
        style={{ 
          position: 'absolute', 
          bottom: '20px', 
          left: '20px', 
          padding: '10px', 
          borderRadius: '5px', 
          color: 'white' 
        }}
      >
        <Typography variant="h4">Author: John Doe</Typography>
        <Typography variant="h4">Generated by: NeuralNet AI</Typography>
        <Typography variant="h4">Prompt: эльфы</Typography>
      </Box>
      <Box 
        style={{ 
          position: 'absolute', 
          top: '40%', 
          left: '50%', 
          transform: 'translate(-50%, -50%)', // Center the panel
          backgroundColor: 'rgba(128, 128, 128, 0.7)', // Gray background with transparency
          padding: '20px', 
          borderRadius: '10px', 
          boxShadow: '0px 4px 10px rgba(0, 0, 0, 0.3)', // Shadow for depth
          width: '80%', // Width of the search panel
          maxWidth: '600px' // Maximum width
        }}
      >
        <TextField 
          variant="outlined" 
          fullWidth 
          placeholder="Найти..." 
          style={{ marginBottom: '10px' }} 
        />
      </Box>
      <Box 
        style={{ 
          position: 'absolute', 
          top: '5%', 
          left: '50%', 
          transform: 'translate(-50%, -50%)', // Center the tags
          padding: '10px', 
          borderRadius: '10px', 
          width: '97%', // Width of the tags panel
          overflowX: 'auto', // Enable horizontal scrolling
          whiteSpace: 'nowrap', // Prevent line breaks
          scrollbarWidth: 'none', // Hide scrollbar for Firefox
          msOverflowStyle: 'none', // Hide scrollbar for Internet Explorer and Edge
        }}
      >
        {tags.map((tag, index) => (
          <Chip 
            key={index} 
            label={tag} 
            onClick={() => handleTagClick(tag)} // Make chip clickable
            style={{ 
              margin: '5px', 
              backgroundColor: 'rgba(128, 128, 128, 0.5)', 
              color: 'white', 
              cursor: 'pointer', // Change cursor to pointer
              fontSize: '1.2rem', // Increase font size
              padding: '10px 15px' // Increase padding for larger chips
            }} 
          />
        ))}
      </Box>
    </Box>
  );
};